kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  jobName: http-get
  interval: 15s
  module: http_2xx
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:19115
    scheme: http 
    path: /probe
  targets:
    staticConfig:
      static:
      - http://posts.com/
      - http://localhost:9090/api/v1/